# Generated by Django 5.2.7 on 2025-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentWeight',
            fields=[
                ('component', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('weight_pct', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PeerBenchmark',
            fields=[
                ('city', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=10)),
                ('benchmark_saving_pct', models.FloatField()),
                ('peer_base_percentile', models.FloatField()),
                ('income_low', models.IntegerField()),
                ('income_high', models.IntegerField()),
                ('mean_adj_low', models.FloatField()),
                ('mean_adj_high', models.FloatField()),
            ],
        ),
    ]
